### ISSUE TITLE
PSFP visualization issues

### ISSUE THREAD

**Issue by anntzer** [kthorn/FPvisualization#1]
When visualizing e.g. emission vs. brightness on the PSFP visualization, boxes representing the FPs tend to disappear as you hover over them.
Tested on Firefox, Chromium and Opera on Linux.

Thanks for the great work!

**Comment by tlambert03** [comment]
indeed!  thanks anntzer.  
I updated the repo.  Kurt will need to update the website as he controls the server.

**Comment by kthorn** [comment]
I updated this on the server.  The fix means that the squares don't expand symmetrically. The commented-out lines of code were supposed to reset the x and y coordinates of the squares so that they would expand symmetrically (they are defined by their upper left corner and height and width) but I don't have time right now to investigate why x and y were not getting set properly when the axes are changed.

**Comment by tlambert03** [comment]
ahah.  figured it out...
when a square entered the DOM on `square.enter().append("rect")`, it was binding the current axis values to the datapoint.  Thus, when the axis are changed, mousing over the element returned it to the X/Y location that was set when the element entered the DOM in the first place (which was often off screen if the axis ranges had changed significantly).
I fixed it in the code by changing `xVar` to `currentX` ... it's possible that the original plot() function i created with the optional xvar and yvar arguments may not have been a good design after all.

**Comment by kthorn** [comment]
On 3/26/2015 8:37 PM, tlambert03 wrote:

> ahah. figured it out...
> when a square entered the DOM on |square.enter().append("rect")|, it 
> was binding the current axis values to the datapoint. Thus, when the 
> axis are changed, mousing over the element returned it to the X/Y 
> location that was set when the element entered the DOM in the first 
> place (which was often off screen if the axis ranges had changed 
> significantly).
> I fixed it in the code but changing |xVar| to |currentX| ... its worth 
> nothing that the original plot() function i created with the optional 
> xvar and yvar arguments may not have been a good design after all.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/kthorn/FPvisualization/issues/1#issuecomment-86807337.
> 
> Thanks!  I've got a lot going on here so don't have time to work on this 
> now, unfortunately.  I'll update the website to the latest code.

Kurt

## 

Kurt Thorn
Associate Professor
Director, Nikon Imaging Center
http://thornlab.ucsf.edu/
http://nic.ucsf.edu/blog/

**Comment by tlambert03** [comment]
Of course!
I think it should be fine to leave it like this.  It's just worth remembering this little pitfall if problems arise in the future with additional enhancements.
Best
Talley
